[0m12:48:22.880872 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1e0d52ba40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1e0cfa7500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1e0d350620>]}


============================== 12:48:22.889041 | be13ccd9-4117-494a-ba32-def9f38cbea2 ==============================
[0m12:48:22.889041 [info ] [MainThread]: Running with dbt=1.9.3
[0m12:48:22.889992 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/carizac/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init etl_project', 'send_anonymous_usage_stats': 'True'}
[0m12:48:22.906367 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/home/carizac/.dbt')}
[0m12:48:22.907185 [info ] [MainThread]: Creating dbt configuration folder at 
[0m12:48:22.910309 [debug] [MainThread]: Starter project path: /home/carizac/dbt-env/lib/python3.12/site-packages/dbt/include/starter_project
[0m12:48:22.917581 [info ] [MainThread]: 
Your new dbt project "etl_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:48:22.918445 [info ] [MainThread]: Setting up your profile.
[0m13:05:58.150078 [error] [MainThread]: Encountered an error:

[0m13:05:58.162688 [error] [MainThread]: Traceback (most recent call last):
  File "/home/carizac/dbt-env/lib/python3.12/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/carizac/dbt-env/lib/python3.12/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/carizac/dbt-env/lib/python3.12/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "/home/carizac/dbt-env/lib/python3.12/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/home/carizac/dbt-env/lib/python3.12/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/home/carizac/dbt-env/lib/python3.12/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/home/carizac/dbt-env/lib/python3.12/site-packages/dbt/task/init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carizac/dbt-env/lib/python3.12/site-packages/dbt/task/init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "/home/carizac/dbt-env/lib/python3.12/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/carizac/dbt-env/lib/python3.12/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m13:05:58.167637 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 1137.8535, "process_in_blocks": "664", "process_kernel_time": 0.259681, "process_mem_max_rss": "106540", "process_out_blocks": "80", "process_user_time": 1.956889}
[0m13:05:58.169955 [debug] [MainThread]: Command `dbt init` failed at 13:05:58.169042 after 1137.86 seconds
[0m13:05:58.172304 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1e0d6d5970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1e0b7a6540>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1e0b8a6f60>]}
[0m13:05:58.174344 [debug] [MainThread]: Flushing usage events
[0m13:05:58.610439 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:08:05.704561 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f34f3e39b20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f34f51ec590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f34f52766f0>]}


============================== 13:08:05.712749 | 08fe2121-a279-402d-adcc-49d509d0c506 ==============================
[0m13:08:05.712749 [info ] [MainThread]: Running with dbt=1.9.3
[0m13:08:05.713989 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/carizac/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init etl_project', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:08:05.746340 [info ] [MainThread]: A project called etl_project already exists here.
[0m13:08:05.748441 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.19252007, "process_in_blocks": "49024", "process_kernel_time": 0.320369, "process_mem_max_rss": "88056", "process_out_blocks": "8", "process_user_time": 1.941064}
[0m13:08:05.749304 [debug] [MainThread]: Command `dbt init` succeeded at 13:08:05.749126 after 0.19 seconds
[0m13:08:05.749925 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f34f4602f30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f34f52766f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f34f4a99100>]}
[0m13:08:05.750515 [debug] [MainThread]: Flushing usage events
[0m13:08:06.188122 [debug] [MainThread]: An error was encountered while trying to flush usage events
